services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    ports:
      - '5432:5432'

networks:
  default:
    name: todo
